# Generated by Django 5.0.4 on 2024-05-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_profile_pic_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaul.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
